import os
import json
from pathlib import Path

PROJECT_ROOT = Path(__file__).parent.parent.parent
SKILL_PATH = PROJECT_ROOT / "agents" / "sk-architect" / "SKILL.md"
STANDARD_SKILL_PATH = PROJECT_ROOT / "agents" / "sk-standard" / "SKILL.md"
WORKFLOW_PATH = PROJECT_ROOT / "agents" / "workflow" / "vba_generation_workflow.md"

def compile_sheet_agent(data: dict) -> str:
    """
    Sử dụng hoàn toàn Agent (LLM) để sinh mã VBA.
    Thực hiện theo vba_generation_workflow.md.
    """
    try:
        import google.generativeai as genai # type: ignore
        api_key = os.environ.get("GOOGLE_API_KEY")
        if not api_key:
            return "' ERROR: GOOGLE_API_KEY chưa được set. Vui lòng export GOOGLE_API_KEY trước."
            
        genai.configure(api_key=api_key)
        
        # Đọc rules
        skill_content = ""
        if WORKFLOW_PATH.exists():
            skill_content += "--- WORKFLOW ---\n" + WORKFLOW_PATH.read_text(encoding="utf-8") + "\n\n"
        if SKILL_PATH.exists():
            skill_content += "--- ARCHITECT SKILL ---\n" + SKILL_PATH.read_text(encoding="utf-8") + "\n\n"
        if STANDARD_SKILL_PATH.exists():
            skill_content += "--- STANDARD SKILL ---\n" + STANDARD_SKILL_PATH.read_text(encoding="utf-8")
            
        # Fallback model
        model = os.environ.get("GEMINI_MODEL", "gemini-2.5-pro")
        m = genai.GenerativeModel(model)
        
        # Dữ liệu compact
        sheet_name = data.get("_meta", {}).get("source_sheet", "Unknown")
        compact_data = {"_meta": data.get("_meta", {})}
        for k in ["出力条件", "通常処理", "特殊処理"]:
            if k in data:
                compact_data[k] = data[k]
                
        prompt = f"""
Bạn là sk-architect, một chuyên gia lập trình VBA Access.
Nhiệm vụ của bạn là sinh toàn bộ mã nguồn VBA (.bas) cho module '{sheet_name}' bằng cách làm theo chính xác các quy tắc và workflow đã cung cấp.

{skill_content}

--- DATA BẢN RÚT GỌN (sheet_raw.json) ---
{json.dumps(compact_data, ensure_ascii=False, indent=2)}

---
YÊU CẦU QUAN TRỌNG:
1. TRẢ VỀ DUY NHẤT MÃ NGUỒN VBA, KHÔNG GIẢI THÍCH, KHÔNG CHIA NHỎ.
2. Tuyệt đối không dùng markdown block (ví dụ ```vba). Chỉ trả về text thuần.
3. Code sinh ra phải có đầy đủ Sub set_..., xoá dữ liệu cũ, init FLG, các block UPDATE, cleanup, footer và log_write đầy đủ theo chuẩn.
"""
        response = m.generate_content(prompt)
        vba_raw = response.text.strip()
        
        if vba_raw.startswith("```"):
            lines = vba_raw.split("\n")
            vba_raw = "\n".join(l for l in lines if not l.startswith("```")).strip()
            
        return (
            "' --- FULLY GENERATED BY AGENT ---\n"
            + vba_raw
            + "\n' --- END AGENT GENERATION ---\n"
        )
        
    except Exception as e:
        return f"' Lỗi khi generate qua Agent: {str(e)}"
